/*
 * Copyright 1999-2018 Alibaba Group Holding Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.microsphere.sentinel.dashboard.rule.apollo;

import io.microsphere.sentinel.dashboard.datasource.entity.rule.FlowRuleEntity;
import io.microsphere.sentinel.dashboard.rule.DynamicRulePublisher;
import com.alibaba.csp.sentinel.datasource.Converter;
import com.alibaba.csp.sentinel.util.AssertUtil;
import com.ctrip.framework.apollo.openapi.client.ApolloOpenApiClient;
import com.ctrip.framework.apollo.openapi.dto.NamespaceReleaseDTO;
import com.ctrip.framework.apollo.openapi.dto.OpenItemDTO;
import io.microsphere.sentinel.util.SentinelUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.util.List;

import static io.microsphere.text.FormatUtils.format;

/**
 * @author hantianwei@gmail.com
 * @author <a href="mailto:mercyblitz@gmail.com">Mercy</a>
 * @since 1.5.0
 */
@Component("apolloFlowRulePublisher")
public class ApolloFlowRulePublisher implements DynamicRulePublisher<List<FlowRuleEntity>> {

    private static final String COMMEND_PATTERN = "Sentinel Flow Rule for application '{}' generated by '{}'";

    @Autowired
    private ApolloOpenConfig config;

    @Autowired
    private ApolloOpenApiClient apolloOpenApiClient;

    @Autowired
    private Converter<List<FlowRuleEntity>, String> converter;

    @Override
    public void publish(String app, List<FlowRuleEntity> rules) throws Exception {
        AssertUtil.notEmpty(app, "app name cannot be empty");
        if (rules == null) {
            return;
        }

        // Increase the configuration
        String appId = config.appId;
        String operator = config.operator;
        String env = config.env;
        String clusterName = config.clusterName;
        String namespace = config.namespace;
        String key = SentinelUtils.getFlowDataId(app);
        String comment = format(COMMEND_PATTERN, app, appId);

        OpenItemDTO openItemDTO = new OpenItemDTO();
        openItemDTO.setKey(key);
        openItemDTO.setValue(converter.convert(rules));
        openItemDTO.setComment(comment);
        openItemDTO.setDataChangeCreatedBy(operator);
        openItemDTO.setDataChangeLastModifiedBy(operator);

        try {
            apolloOpenApiClient.createItem(appId, env, clusterName, namespace, openItemDTO);
        } catch (Throwable e) {
            apolloOpenApiClient.updateItem(appId, env, clusterName, namespace, openItemDTO);
        }

        // Release configuration
        NamespaceReleaseDTO namespaceReleaseDTO = new NamespaceReleaseDTO();
        namespaceReleaseDTO.setEmergencyPublish(true);
        namespaceReleaseDTO.setReleaseComment(comment);
        namespaceReleaseDTO.setReleasedBy(operator);
        namespaceReleaseDTO.setReleaseTitle("Release " + comment);
        apolloOpenApiClient.publishNamespace(appId, env, clusterName, namespace, namespaceReleaseDTO);
    }
}
